"""empty message

Revision ID: 1553865ad157
Revises: None
Create Date: 2015-07-01 18:37:45.809539

"""

# revision identifiers, used by Alembic.
revision = '1553865ad157'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lolcommit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('author_email', sa.String(), nullable=True),
    sa.Column('sha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lolcommit')
    ### end Alembic commands ###
